sdCanvas = False				# Depends on: sdTooltip
sdCharts = False				# Depends on: -
sdCheckbutton = False			# Depends on: sdCanvas
sdChecksum = False				# Depends on: -
sdDatabase = False				# Depends on: sdIniParser
sdDate = False					# Depends on: sdCanvas, sdCheckbutton, sdDatePicker, sdEntryWidget, sdMessageBox
sdDatePicker = False			# Depends on: sdCanvas, sdEntryWidget
sdEntryWidget = False			# Depends on: sdTooltip
#sdIniParser = True				# This is loaded by default by sdCommon library
sdInput = False					# Depends on: sdCanvas
sdListBoxMultiColumn = False	# Depends on: -
sdLogger = False				# Depends on: -
sdMessageBox = False			# Depends on: sdCanvas
sdNamedPipe = False				# Depends on: -
sdNotification = False			# Depends on: sdCanvas
sdNumberRange = False			# Depends on: sdEntryWidget
sdProgressBar = False			# Depends on: -
sdTime = False					# Depends on: sdCanvas, sdEntryWidget
sdTimePicker = False			# Depends on: -
sdTimer = False					# Depends on: -
sdTooltip = False				# Depends on: -
