sdCanvas = True					# Depends on: sdTooltip
sdCharts = False				# Depends on: -
sdCheckbutton = True			# Depends on: sdCanvas
sdChecksum = False				# Depends on: -
sdDatabase = False				# Depends on: sdIniParser
sdDate = True					# Depends on: sdCanvas, sdCheckbutton, sdDatePicker, sdEntryWidget, sdMessageBox
sdDatePicker = True				# Depends on: sdCanvas, sdEntryWidget
sdEntryWidget = True			# Depends on: sdTooltip
#sdIniParser = True				# This is loaded by default by sdCommon library
sdInput = False					# Depends on: -
sdListBoxMultiColumn = False	# Depends on: -
sdLogger = False				# Depends on: -
sdMessageBox = True				# Depends on: sdCanvas
sdNamedPipe = False				# Depends on: -
sdNotification = False			# Depends on: sdCanvas
sdNumberRange = False			# Depends on: sdEntryWidget
sdProgressBar = False			# Depends on: -
sdTimePicker = False			# Depends on: -
sdTimer = False					# Depends on: -
sdTooltip = True				# Depends on: -
